// flow-typed signature: b3645d645f6b70929b30d3f860bd5b18
// flow-typed version: <<STUB>>/profanity-analysis_v0.0.5/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'profanity-analysis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'profanity-analysis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'profanity-analysis/lib/curseWords/index' {
  declare module.exports: any;
}

declare module 'profanity-analysis/lib/profanityAnalysis' {
  declare module.exports: any;
}

declare module 'profanity-analysis/test/profanityAnalysis' {
  declare module.exports: any;
}

// Filename aliases
declare module 'profanity-analysis/lib/curseWords/index.js' {
  declare module.exports: $Exports<'profanity-analysis/lib/curseWords/index'>;
}
declare module 'profanity-analysis/lib/profanityAnalysis.js' {
  declare module.exports: $Exports<'profanity-analysis/lib/profanityAnalysis'>;
}
declare module 'profanity-analysis/test/profanityAnalysis.js' {
  declare module.exports: $Exports<'profanity-analysis/test/profanityAnalysis'>;
}
