// flow-typed signature: 8d7d21454823809c8ce337db0c229d9c
// flow-typed version: <<STUB>>/trie-search_v^1.0.9/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'trie-search'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'trie-search' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'trie-search/performance' {
  declare module.exports: any;
}

declare module 'trie-search/src/TrieSearch' {
  declare module.exports: any;
}

declare module 'trie-search/test/TrieSearchTest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'trie-search/index' {
  declare module.exports: $Exports<'trie-search'>;
}
declare module 'trie-search/index.js' {
  declare module.exports: $Exports<'trie-search'>;
}
declare module 'trie-search/performance.js' {
  declare module.exports: $Exports<'trie-search/performance'>;
}
declare module 'trie-search/src/TrieSearch.js' {
  declare module.exports: $Exports<'trie-search/src/TrieSearch'>;
}
declare module 'trie-search/test/TrieSearchTest.js' {
  declare module.exports: $Exports<'trie-search/test/TrieSearchTest'>;
}
