// flow-typed signature: 3e709113153c16d1e8544f34912149c8
// flow-typed version: <<STUB>>/word-list-json_v^0.2.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'word-list-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'word-list-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'word-list-json/index' {
  declare module.exports: $Exports<'word-list-json'>;
}
declare module 'word-list-json/index.js' {
  declare module.exports: $Exports<'word-list-json'>;
}
