// flow-typed signature: c6c0fb6542f0af8047fea3540e7e5aea
// flow-typed version: <<STUB>>/wordlist-english_v^1.1.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wordlist-english'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wordlist-english' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'wordlist-english/index' {
  declare module.exports: $Exports<'wordlist-english'>;
}
declare module 'wordlist-english/index.js' {
  declare module.exports: $Exports<'wordlist-english'>;
}
