// @flow
const INIT_WORDS: "INIT_WORDS" = "INIT_WORDS";
const CHECK_WORD: "CHECK_WORD" = "CHECK_WORD";
const PUSH_LETTER: "PUSH_LETTER" = "PUSH_LETTER";
const POP_LETTER: "POP_LETTER" = "POP_LETTER"

export default {
	INIT_WORDS, CHECK_WORD, PUSH_LETTER, POP_LETTER
}