// @flow
export const INIT_LETTERS: "INIT_LETTERS" = "INIT_LETTERS";
export const PUSH_LETTER: "PUSH_LETTER" = "PUSH_LETTER";
export const POP_LETTER: "POP_LETTER" = "POP_LETTER";
export const SHUFFLE_LETTERS: "SHUFFLE_LETTERS" = "SHUFFLE_LETTERS";
export const INIT_WORDS: "INIT_WORDS" = "INIT_WORDS";
export const CHECK_WORD: "CHECK_WORD" = "CHECK_WORD";

export default {
	INIT_LETTERS,
	PUSH_LETTER,
	POP_LETTER,
	SHUFFLE_LETTERS,
	INIT_WORDS,
	CHECK_WORD,
};
